### ISSUE TITLE
datasets are disable to download

### ISSUE THREAD

**Issue by JasonSun623** [ut-amrl/hitl-slam#1]

**Comment by Hui-Lin** [comment]
The same question. Is there any instruction of downloading dataset using owncloudx ?

**Comment by SamerNashed** [comment]
Hi, sorry about that - we were switching server locations. The links in the README have been updated and should point you to the correct locations to download data. Let me know if there are any more issues.

**Comment by JasonSun623** [comment]
thank you so much

**Comment by Hui-Lin** [comment]
> Hi, sorry about that - we were switching server locations. The links in the README have been updated and should point you to the correct locations to download data. Let me know if there are any more issues.

Thanks.
