### ISSUE TITLE
ConfigReader: /config/common.cfg: File not found

### ISSUE THREAD

**Issue by JasonSun623** [ut-amrl/hitl-slam#2]
Hello
 run ./bin/localization_gui and get this error:
Vector Localization GUI

[rospack] Error: package 'cobot_linux' not found
[librospack]: error while executing command
[rospack] Error: package 'cobot_linux' not found
[librospack]: error while executing command
ConfigReader: cannot open /config/common.cfg: No such file or directory
ConfigReader: /config/common.cfg: File not found
ConfigReader: cannot open /../robot.cfg: No such file or directory
ConfigReader: /../robot.cfg: File not found
ConfigReader: cannot open /config/non_markov_localization.cfg: No such file or directory
ConfigReader: /config/non_markov_localization.cfg: File not found
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
looking forward to your reply!

**Comment by SamerNashed** [comment]
I've pushed a fix, try re-compiling and running again.
